"""Generate a standalone Pipe from the canonical Workspace Tool; no runtime repo import."""
from pathlib import Path


def render(root):
    tool = (root / 'openwebui/tools/trading212_demo_gateway_v03_selfcontained.py').read_text()
    footer = (root / 'openwebui/templates/trading212_demo_pipe.py.inc').read_text()
    return '# GENERATED by scripts/build_t212_demo_pipe.py; edit canonical Tool/template.\n' + tool.rstrip() + '\n\n\n' + footer


if __name__ == '__main__':
    root = Path(__file__).resolve().parents[1]
    (root / 'openwebui/trading212_demo_execution.py').write_text(render(root))
